In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2025-02-12 14:05:42.991439: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-02-12 14:05:43.240449: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-02-12 14:05:43.240547: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-02-12 14:05:43.281709: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-02-12 14:05:43.367119: I tensorflow/core/platform/cpu_feature_guar

In [2]:
### sentences
sent=[
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000

In [5]:
#one hot represnetation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7323, 1786, 5316, 9244, 5656],
 [749, 4558, 2968, 921, 1001],
 [1685, 2953, 2854, 9244]]

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
#padding the sequencesof sentence to get same length of sentence
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 7323 1786 5316 9244 5656]
 [   0    0    0  749 4558 2968  921 1001]
 [   0    0    0    0 1685 2953 2854 9244]]


In [9]:
## feature representation
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 72ms/step


array([[[ 2.7834069e-02, -2.1692013e-02,  3.4785200e-02, -2.0324588e-03,
         -2.8419042e-02, -5.4354072e-03, -1.5451968e-02,  2.4625063e-03,
          4.1884188e-02,  4.3957863e-02],
        [ 2.7834069e-02, -2.1692013e-02,  3.4785200e-02, -2.0324588e-03,
         -2.8419042e-02, -5.4354072e-03, -1.5451968e-02,  2.4625063e-03,
          4.1884188e-02,  4.3957863e-02],
        [ 2.7834069e-02, -2.1692013e-02,  3.4785200e-02, -2.0324588e-03,
         -2.8419042e-02, -5.4354072e-03, -1.5451968e-02,  2.4625063e-03,
          4.1884188e-02,  4.3957863e-02],
        [ 4.6870980e-02,  2.0851921e-02,  8.8922009e-03,  2.0752121e-02,
         -3.4295190e-02,  2.8588142e-02,  3.1169485e-02,  3.4568656e-02,
          2.7339410e-02, -4.9116161e-02],
        [-2.3681546e-02,  3.7996996e-02, -9.8360069e-03, -3.1316567e-02,
          1.8509235e-02,  4.2423043e-02,  4.2005662e-02,  4.0059712e-02,
         -3.3658698e-02, -4.6881344e-02],
        [-4.7633138e-02,  2.2741351e-02,  3.1058516e-02, -2.

In [13]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 24ms/step


array([[ 0.02783407, -0.02169201,  0.0347852 , -0.00203246, -0.02841904,
        -0.00543541, -0.01545197,  0.00246251,  0.04188419,  0.04395786],
       [ 0.02783407, -0.02169201,  0.0347852 , -0.00203246, -0.02841904,
        -0.00543541, -0.01545197,  0.00246251,  0.04188419,  0.04395786],
       [ 0.02783407, -0.02169201,  0.0347852 , -0.00203246, -0.02841904,
        -0.00543541, -0.01545197,  0.00246251,  0.04188419,  0.04395786],
       [ 0.04687098,  0.02085192,  0.0088922 ,  0.02075212, -0.03429519,
         0.02858814,  0.03116949,  0.03456866,  0.02733941, -0.04911616],
       [-0.02368155,  0.037997  , -0.00983601, -0.03131657,  0.01850924,
         0.04242304,  0.04200566,  0.04005971, -0.0336587 , -0.04688134],
       [-0.04763314,  0.02274135,  0.03105852, -0.0217507 ,  0.01433006,
         0.0243952 , -0.01581113, -0.0458694 ,  0.01476437,  0.03567806],
       [ 0.0431577 , -0.01083719, -0.01216034,  0.04010272, -0.00522959,
        -0.01741904, -0.02652229, -0.04573119

In [14]:
embedded_docs[0]

array([   0,    0,    0, 7323, 1786, 5316, 9244, 5656], dtype=int32)